version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html


# volumes kısmında html-data adında bir volume tanımlandı. 
# Bu volume, konteynerdeki /usr/share/nginx/html diziniyle eşleştiriliyor.